import json

# this script starts with manually ingested LaTeX formatted sections (generated via ChatGPT from raw PDF) from 
# the MRTX1133 paper (PMID 36216931) and generates a JSON

data = {
    "sections": [
        {
            "section_id": "Abstract",
            "major_heading": "Abstract",
            "subheading_index": None,      
            "section_text":r'The ability to effectively target mutated KRAS has remained elusive despite decades of research. The recent identification of KRAS$^{\mathrm{G12C}}$ inhibitors has provided an effective treatment option for patients harboring this particular mutation and has also provided insight toward targeting other KRAS mutants, including KRAS$^{\mathrm{G12D}}$. MRTX1133 was identified via a structure-based drug design (SBDD) strategy as a potent, selective, and non-covalent KRAS$^{\mathrm{G12D}}$ inhibitor directed at the switch II binding pocket. MRTX1133 demonstrated a high-affinity interaction with KRAS$^{\mathrm{G12D}}$ with $K_D$ or IC$_{50}$ values each determined at $\sim 0.2$ pM or $<2$ nM using SPR direct binding or HTRF competition assays, respectively. MRTX1133 also demonstrated $\sim 700$-fold selectivity for KRAS$^{\mathrm{G12D}}$ vs KRAS$^{\mathrm{WT}}$ binding utilizing SPR. Interestingly, MRTX1133 demonstrated potent inhibition of active KRAS$^{\mathrm{G12D}}$ using an HTRF effector interaction assay with an IC$_{50}$ value of 9 nM. Insight toward the structural basis of binding of MRTX1133 to both the inactive GDP-bound and active GMPPCP-bound conformations of KRAS$^{\mathrm{G12D}}$ is also provided by co-crystal structures. MRTX1133 demonstrated potent inhibition of ERK1/2 phosphorylation and cell viability in KRAS$^{\mathrm{G12D}}$-mutant cell lines with median IC$_{50}$ values of $\sim 5$ nM. Consistent with binding affinity determination in cell-free systems, MRTX1133 demonstrated $>1000$-fold selectivity for inhibition of ERK1/2 phosphorylation in KRAS$^{\mathrm{G12D}}$-mutant cell lines compared with KRAS$^{\mathrm{WT}}$ cell lines. Dose-dependent inhibition of KRAS-mediated signal transduction was also observed in multiple KRAS$^{\mathrm{G12D}}$-mutant tumor models \textit{in vivo}. MRTX1133 demonstrated marked tumor regression ($\geq 30\%$) in a subset ($\geq 30\%$) in a subset of KRAS$^{\mathrm{G12D}}$-mutant cell line- and patient-derived xenograft (PDX) models, including 8 out of 11 (73\%) pancreatic ductal adenocarcinoma (PDAC) models evaluated. Pharmacological studies and CRISPR-based screens demonstrated co-targeting KRAS$^{\mathrm{G12D}}$ in concert with putative feedback or bypass pathways including EGFR and PI3K$\alpha$ led to enhanced anti-tumor activity relative to targeting each individual protein. Together, these data indicate the feasibility of utilizing SBDD approaches to selectively target alternative KRAS mutant variants with non-covalent, high-affinity small molecules targeting either the active or inactive state of KRAS. In addition, these data illustrate the therapeutic susceptibility and broad dependence of KRAS$^{\mathrm{G12D}}$ mutation-positive tumors, including PDAC, on KRAS for tumor cell growth and survival.'
        },
        {
            "section_id": "Significance",
            "major_heading": "Significance",
            "subheading_index": None,        
            "section_text":r'The development of clinically active KRAS$^{\mathrm{G12C}}$-selective inhibitors represents a milestone achievement for the treatment of cancer; however, the discovery of additional KRAS-mutant selective inhibitors has remained elusive. MRTX1133 is a potent KRAS$^{\mathrm{G12D}}$-selective small molecule inhibitor, is active \textit{in vitro} and \textit{in vivo}, induces regression in multiple xenograft tumor models and demonstrates increased anti-tumor activity in rationally designed combinations. These data confirm KRAS$^{\mathrm{G12D}}$ functions as an oncogenic driver, including in pancreatic and colorectal cancers, and provide insight into the development of therapeutic strategies for patients with this mutation---which is 3-fold more prevalent than KRAS$^{\mathrm{G12C}}$ and reflects a significant unmet need.'
        },
        {   
            "section_id": "Introduction",
            "major_heading": "Introduction",
            "subheading_index": None,       
            "section_text":r"""\textit{KRAS} is one of the most frequently mutated oncogenes in cancer, yet efforts to directly target KRAS have been mostly unsuccessful because initial analyses of KRAS proteins indicated that they lack a clear pocket to which small molecules can bind with high affinity [1, 2]. However, covalent inhibitors targeting the mutated cysteine residues in KRAS$^{\mathrm{G12C}}$ exploited a binding pocket in the switch II domain which enabled the development of clinically active small molecule inhibitors for patients with this mutation [3--5]. The switch II binding pocket present in all KRAS proteins may represent a feasible binding surface for the development of additional KRAS inhibitors, including mutant-selective inhibitors.

            \textit{KRAS}$^{\mathrm{G12D}}$ is the most common \textit{KRAS} mutation and is present in approximately 34\% of pancreatic cancer, 10--12\% of colorectal cancer, 4\% of lung adenocarcinoma, 11\% of bile duct carcinoma, 5\% of endometrial cancer, and a number of other cancer types [6]. It is clear that KRAS$^{\mathrm{G12D}}$ is a compelling cancer target; however, there are a series of challenges that need to be overcome to effectively target other KRAS mutant variants. Unlike KRAS$^{\mathrm{G12C}}$, KRAS$^{\mathrm{G12D}}$ lacks a reactive residue proximal to the switch II binding pocket to enable covalent modification of the protein, therefore novel approaches are required to develop selective inhibitors with high affinity and drug-like potency. Moreover, the appreciable degree of nucleotide cycling observed in KRAS$^{\mathrm{G12C}}$-mutant protein proved critical for the development of clinically active KRAS$^{\mathrm{G12C}}$-selective inhibitors which bind the GDP-bound conformation and lock KRAS in the inactive state [7--9]. KRAS$^{\mathrm{G12D}}$ reportedly has the second highest intrinsic GTP hydrolysis rate among KRAS mutants as well as the highest rate of GTPase-activating protein (GAP)-mediated GTP hydrolysis, albeit much lower than KRAS$^{\mathrm{WT}}$ [7]. KRAS$^{\mathrm{G12D}}$ nucleotide cycling may therefore influence the importance of targeting the inactive versus active states. Finally, the level of oncogene addiction to KRAS$^{\mathrm{G12D}}$ in cancers harboring this mutation is not fully understood and will pose a critical question to enable effective development of inhibitors and therapeutic regimens directed at this particular mutation. Here, we have identified and characterized a selective and non-covalent high-affinity KRAS$^{\mathrm{G12D}}$ inhibitor illustrating the feasibility of targeting this key mutant variant and facilitating a deeper understanding of the role of these mutations in cancer pathogenesis and progression."""
        },
        {
            "section_id": r"MRTX1133 is a Potent and Selective KRAS$^{\mathrm{G12D}}$ Inhibitor",
            "major_heading": "Results",
            "subheading_index": 1,      
            "section_text":r"""A structure-based drug design strategy was used to identify MRTX1133, a potent and selective KRAS$^{\mathrm{G12D}}$ inhibitor [10] (Fig.~1A). Utilizing surface plasmon resonance (SPR) to directly measure binding, MRTX1133 demonstrated $\sim 700$-fold selectivity for binding to GDP-bound KRAS$^{\mathrm{G12D}}$ compared to KRAS$^{\mathrm{WT}}$ (GDP-bound KRAS$^{\mathrm{G12D}}$ $K_D = \sim 0.2$ pM versus GDP-bound KRAS$^{\mathrm{WT}}$ $K_D = 140$ nM) (Fig.~1B). In a biochemical HTRF assay designed to measure displacement of a labeled probe molecule from the switch II pocket of KRAS, MRTX1133 demonstrated binding to the GDP-bound, inactive form of KRAS$^{\mathrm{G12D}}$ with an IC$_{50} < 2$ nM, which was the lower limit of detection of the assay (Fig.~1B). Utilizing an HTRF assay pre-loaded with a non-hydrolysable GTP analog, MRTX1133 also inhibited the binding of a RAF-RAS binding domain (RBD) peptide to the active form of KRAS$^{\mathrm{G12D}}$ with an IC$_{50}$ of 9 nM (Fig.~1B). X-ray crystal structures of KRAS$^{\mathrm{G12D}}$/MRTX1133 co-complexed with GDP [10] and with GMPPCP, a non-hydrolysable GTP analog (Fig.~1C and S1A), support the observed inhibitor potency in both active and inactive states of KRAS$^{\mathrm{G12D}}$. Furthermore, binding of MRTX1133 to KRAS$^{\mathrm{G12D}}$ resulted in a conformational change of Switch I and Switch II, loops that are involved in protein-protein interactions with downstream effector molecules. The resulting conformation is observed in both the GDP and GMPPCP co-complexed structures suggesting that MRTX1133 binding, independent of nucleotide state, eliminates KRAS$^{\mathrm{G12D}}$ protein surface competency for binding effector proteins (Fig.~S1A). Combined, these data demonstrate MRTX1133 potently and selectively binds both the active and inactive forms of KRAS$^{\mathrm{G12D}}$. Although MRTX1133 appears to more potently inhibit the inactive form of KRAS$^{\mathrm{G12D}}$, it is possible that MRTX1133 binding to the active form may contribute to its mechanism of inhibition of KRAS$^{\mathrm{G12D}}$ in cells harboring this mutation.

            Given the potency and selectivity for KRAS$^{\mathrm{G12D}}$ protein in the biochemical assays, MRTX1133 was evaluated in cellular assays designed to evaluate its effect on KRAS signaling and cell viability. Following a 3-hour treatment in the KRAS$^{\mathrm{G12D}}$-mutant, HPAC (pancreatic) and GP2D (colorectal) cancer cell lines, MRTX1133 demonstrated concentration-dependent inhibition of key KRAS pathway signaling molecules including phosphorylated extracellular signal-regulated kinase 1/2 (pERK), phosphorylated S6 (pS6), phosphorylated 4EBP1 (p4EBP1) and dual specificity phosphatase 4 or 6 (DUSP4/6) expression (Fig.~1D, E, S1B and S1C). The IC$_{50}$ value for pERK and pS6 inhibition was $\leq 3$ nM in both cell lines. MRTX1133 was evaluated at selected concentrations (0, 1, 10 and 100 nM) over a time course in the HPAC cell line. MRTX1133 demonstrated similar IC$_{50}$ values and persistent inhibition of pERK and pS6 as early as 3 hours through 72 hours of treatment with DUSP4 inhibition kinetics generally tracking with inhibition of pERK and pS6 (Fig.~1F). In contrast, inhibition of p4EBP1 and DUSP6 expression was delayed compared with pERK and pS6, which may indicate these pathway nodes are differentially regulated. Of note, total ERK and S6 protein levels were also decreased at the 48 and 72-hour time points suggesting a potential impact of MRTX1133 on total protein expression and/or cell viability at later time points. In GP2D cells, inhibition of pERK and pS6 is evident from 1 to 24 hours; however, partial reactivation of these proteins was apparent at later time points, suggesting involvement of time-dependent feedback pathways in this cell line (Fig.~S1D). This conclusion is also suggested by the lack of inhibition of DUSP4, DUSP6, and p4EBP1 in GP2D cells."""
        },
        {
            "section_id": r"MRTX1133 is Broadly Active and Demonstrates Selective Inhibition of KRAS-Dependent Signaling and Cell Viability in KRAS$^{\mathrm{G12D}}$ Mutated Cancer Cells",
            "major_heading": "Results",
            "subheading_index": 2,      
            "section_text":r"""MRTX1133 was evaluated for its ability to inhibit KRAS-dependent signaling using a pERK In-Cell Western assay across a panel of 25 KRAS$^{\mathrm{G12D}}$ and 7 non-KRAS$^{\mathrm{G12D}}$-mutant cancer cell lines (Fig.~S2). MRTX1133 potently inhibited pERK in 24 of 25 KRAS$^{\mathrm{G12D}}$-mutant cell lines with IC$_{50}$ values ranging from 0.6--13.7 nM (median IC$_{50}$: 6.1 nM). In contrast, IC$_{50}$ values ranged from 151 to $>3{,}000$ nM (median IC$_{50}$: $>3{,}000$ nM) in the non-KRAS$^{\mathrm{G12D}}$-mutant cell lines evaluated. Using a CellTiter-Glo assay, MRTX1133 inhibited the viability of KRAS$^{\mathrm{G12D}}$-mutant lines with IC$_{50}$ values ranging from 1.4 nM to 42.3 nM (median IC$_{50}$: 5.3 nM) for all but one of the cell lines in the 3D assay format and between 1.5 nM to 299 nM (median IC$_{50}$: 26 nM) in 23 out of 25 cell lines in the 2D assay format. The effect of MRTX1133 on the viability of non-KRAS$^{\mathrm{G12D}}$-mutant cell lines were only observed at higher concentrations with IC$_{50}$ values ranging from 211 nM to $>1{,}000$ nM (median IC$_{50}$: 573 nM) in the 3D assay format and between 103 nM to 3000 nM (median IC$_{50}$: 3000 nM) in the 2D assay format. These data demonstrate MRTX1133 potently and selectively inhibits KRAS-dependent signaling and viability in the vast majority of KRAS$^{\mathrm{G12D}}$-mutant cancer cell lines."""
        },
        {
            "section_id": r"MRTX1133 Demonstrates Inhibition of KRAS-Dependent Signaling and Marked Tumor Regression in KRAS$^{\mathrm{G12D}}$-mutant Xenograft Models",
            "major_heading": "Results",
            "subheading_index": 3,      
            "section_text":r"""MRTX1133 was evaluated in immunocompromised mice bearing KRAS$^{\mathrm{G12D}}$-mutant HPAC tumor xenografts for its effect on KRAS-mediated signaling and to characterize its anti-tumor activity over a range of dose levels and time points. MRTX1133 was administered at 3, 10 and 30 mg/kg dose levels via intraperitoneal (IP) injection to achieve sufficient systemic plasma exposure in mice (Fig.~S3A) and demonstrated complete pERK inhibition at both 1 and 6 hours post-dose in cancer cells using immunohistochemistry supplemented with an image analysis algorithm designed to evaluate the fraction of biomarker-positive tumor cells (Fig.~2A). Dose-dependent reduction of the pERK-positive cell fraction was observed at the 12 and 24-hour post-dose time points indicating partial recovery of this pathway at lower dose levels. The percentage of cancer cells expressing pS6 also exhibited a trend towards reduction in MRTX1133-treated tumors compared to vehicle-treated tumors with near complete inhibition observed at 1 and 6 hours post dose and a dose-dependent recovery by 12 and 24 hours at lower dose levels. Consistent with inhibition of KRAS-dependent signaling pathways, active RAS levels were determined in HPAC tumor lysates and reduced RAS activity was observed at each post-administration time point up to 24 hours (Fig.~2B). MRTX1133 was well-tolerated at dose levels administered IP at up to 30 mg/kg twice daily (BID) in repeat-dose studies for up to 28 days with no evidence of weight loss or overt signs of toxicity (Fig.~S3B). In a repeat-dose study, daily IP administration of MRTX1133 demonstrated dose-dependent anti-tumor efficacy, leading to near complete responses (85\% regression) in mice administered 30 mg/kg BID, 16\% regression at the 10 mg/kg BID dose level, and 81\% tumor growth inhibition at 3 mg/kg BID (Fig.~2C). In the HPAC model, the percentage of cells positive for cleaved caspase-3 staining was increased with MRTX1133 treatment at all dose levels at 12 hours post treatment and at 30 mg/kg at both 12- and 24-hours post-treatment (Fig.~2A). Thus, tumor regression observed was consistent with induction of apoptosis in the HPAC model.
            
            MRTX1133 was also evaluated for its impact on KRAS-dependent signaling and anti-tumor efficacy in additional KRAS$^{\mathrm{G12D}}$-mutant xenograft models. In the Panc 04.03 model, active RAS levels in tumor lysates were significantly reduced 1 and 12 hours post administration of MRTX1133 at 3, 10 or 30 mg/kg administered IP for 3 consecutive doses at 12-hour intervals (Fig.~2D). Active RAS was also evaluated 24-hours following the final dose in the 30 mg/kg group, at which point active RAS remained inhibited. Administration of MRTX1133 also demonstrated dose-dependent inhibition of pERK in tumor lysates at 1 hour post last dose in the BID $\times$ 7 Days cohorts; however, pERK recovery was observed by the 12-hour timepoint at each dose level (Fig.~2E). Interestingly, pERK recovery at 12 hours post-dose appeared to be incomplete after 3 consecutive doses compared with the complete pERK rebound observed after 7 days of BID administration suggesting pERK reactivation pathways may be increasingly engaged over longer administration schedules (Fig.~2E). MRTX1133 demonstrated dose-dependent anti-tumor efficacy over a repeat-dose schedule in the Panc 04.03 model including marked regression at both the 10 and 30 mg/kg BID dose levels (60\% and 74\%, respectively) and approximate tumor stasis at 3 mg/kg BID (Fig.~2F). The similar degree of regression in the 10 and 30 mg/kg BID dose groups suggests 10 mg/kg BID is the maximally effective dose in the Panc 04.03 model. In the GP2D tumor model, a single dose of 30 mg/kg MRTX1133 was administered and prominent inhibition of pERK by immunoblot at 1- and 6-hours post-dose with partial rebound by 12 hours was observed along with marked tumor regression (63\%) over a BID repeat administration schedule (Fig.~S3C and S3D)."""
        },
        {
            "section_id": r"MRTX1133 Demonstrates Broad-spectrum Anti-tumor Activity in KRAS$^{\mathrm{G12D}}$-mutant Cell Line-derived and Patient-derived Xenograft Models and Magnitude of Response was Distinct Between PDAC and CRC Models",
            "major_heading": "Results",
            "subheading_index": 4,      
            "section_text":r"""To evaluate the breadth of anti-tumor activity across genetically and histologically heterogeneous KRAS$^{\mathrm{G12D}}$-mutant models, MRTX1133 was tested at a fixed dose of 30 mg/kg BID administered IP in a panel of human cell line-derived and patient-derived xenografts. MRTX1133 induced 30\% or greater tumor regression in 11/25 KRAS$^{\mathrm{G12D}}$-mutant models (Fig.~3A). The extent of MRTX1133 anti-tumor activity was particularly notable in pancreatic cancer models where 8/11 (73\%) exhibited 30\% or greater tumor regression (Fig.~S4A). By comparison, $\geq 30\%$ regression was observed in 2/8 (25\%) CRC models. MRTX1133 did not demonstrate significant anti-tumor efficacy in all four non-KRAS$^{\mathrm{G12D}}$-mutant models tested. While treatment with MRTX1133 led to marked anti-tumor activity in most models tested, a subset of models was less sensitive to MRTX1133 and exhibited tumor growth inhibition or stable disease as a best response. Bioinformatic analyses were performed to identify molecular biomarkers that correlate with anti-tumor activity. Lower \textit{PTEN} and \textit{CDKN2A} RNA expression was associated with reduced anti-tumor activity, however, neither trend reached statistical significance (Fig.~S4B and S4C). These data suggest co-occurring molecular alterations, including those resulting in altered expression of selected genes, may modify the response to MRTX1133 treatment (Fig.~3A). Overall, these data confirm KRAS$^{\mathrm{G12D}}$ functions as an oncogenic driver across multiple cancer types and that inhibition of KRAS$^{\mathrm{G12D}}$ by MRTX1133 demonstrates KRAS$^{\mathrm{G12D}}$-mediated and tumor-type-dependent efficacy, including marked cytoreductive activity in the majority of PDAC models."""
        },
        {
            "section_id": r"MRTX1133 Inhibits KRAS Signaling and Tumor Growth in an Orthotopic Pancreatic Cancer Model",
            "major_heading": "Results",
            "subheading_index": 5,      
            "section_text":r"""Pancreatic cancer is characterized by a strong desmoplastic reactive stroma comprised of fibroblasts and extracellular matrix components arising from pancreatic stellate cells and features unique to the pancreas. The desmoplastic reaction has been implicated in limiting tissue distribution of small molecule therapies, thereby mediating resistance [11, 12]. Therefore, the ability of MRTX1133 to inhibit KRAS signaling and demonstrate anti-tumor activity in an orthotopic pancreatic cancer model derived from the AsPC-1 cell line was explored. The pathology analysis of hematoxylin and eosin (H\&E) stained sections from orthotopically implanted AsPC-1 tumors displayed an increase in the relative stromal components in the orthotopically implanted tumors compared to subcutaneous tumors, indicating the orthotopic pancreatic tumor model better recapitulated the desmoplastic reactive phenotype expected from pancreatic ductal adenocarcinoma (Fig.~S5A). After 28 days of administration, MRTX1133 administered at 30 mg/kg BID demonstrated significant anti-tumor activity in the orthotopic AsPC-1 model compared to vehicle (Fig.~3B) and the magnitude of tumor response was comparable to that observed for the same model implanted subcutaneously (Fig.~S5B and Fig.~S5C). In addition, MRTX1133 treatment demonstrated pERK inhibition in tumor lysates by immunoblot after 3 consecutive doses and also at end of study (Fig.~S5D). Together, these results indicate sufficient distribution of MRTX1133 to orthotopically implanted pancreatic ductal adenocarcinoma tumors resulting in inhibition of KRAS-dependent signaling and anti-tumor efficacy comparable to ectopically implanted tumors."""
        },
        {
            "section_id": r"Regulation of KRAS-dependent Oncogenic Signaling and Feedback Inhibitory Pathways with MRTX1133 Treatment",
            "major_heading": "Results",
            "subheading_index": 6,      
            "section_text":r"""A comprehensive analysis was conducted to evaluate MRTX1133-induced temporal molecular changes to further interrogate mechanisms of drug response across cell lines or tumor models with varying degrees of sensitivity to MRTX1133. Evaluation of global gene expression was evaluated in A427, LS180, SNU-1033, AsPC-1, and AGS cell lines treated with MRTX1133 and harvested at 3 and 24 hours post treatment for RNAseq analysis. To evaluate changes in global gene expression \textit{in vivo}, xenograft-bearing mice were administered vehicle or 30 mg/kg MRTX1133 via IP every 12 hours for 3 consecutive doses and RNAseq was performed on tumors at 6 and 24 hours post-last dose for LS180 and AsPC-1 models, and at 1, 6, 12, and 24 hours post-last dose for the HPAC model. The top differentially expressed Gene Set Enrichment Analysis (GSEA) pathways for all cell lines and models, regardless of intrinsic sensitivity to MRTX1133, included KRAS signaling UP, KRAS signaling DOWN, MYC targets, MTORC1, E2F targets, and G2M checkpoint pathway signatures (Fig.~4). Consistent with inhibition of RAS signaling, MRTX1133 demonstrated clear reduction in expression of MAPK-dependent target genes DUSP4, DUSP6, ETV4, SPRY4, and PHLDA1 (Fig.~S6A). In addition, MRTX1133 treatment demonstrated time-dependent reduction in MYC, DNA repair, E2F target and cell cycle regulatory genes including Cyclins B, D, and E independent of sensitivity to MRTX1133 across cell lines \textit{in vitro} (Fig.~S6B). Pro-apoptotic genes BBC3, BCL2L11 and BMF were significantly upregulated, while pro-survival genes BIRC5, MCL1, and BCL2L1 were downregulated with MRTX1133 (Fig.~S6B). The relative magnitude of change in expression of key cell cycle genes in AsPC-1 and AGS cell lines compared to the other cell lines tested aligns well with their increased sensitivity to MRTX1133 treatment \textit{in vivo}."""        
        },
        {
            "section_id": r"Co-targeting KRAS$^{\mathrm{G12D}}$ and Feedback or Bypass Pathways Leads to Enhanced Anti-tumor Activity",
            "major_heading": "Results",
            "subheading_index": 7,      
            "section_text":r"""To evaluate the potential for enhanced anti-tumor activity by co-targeting KRAS$^{\mathrm{G12D}}$ and feedback or bypass pathways, pharmacological and CRISPR-based screens were performed. Pharmacological screens were performed in the HPAC cell line using a panel of 28 small molecule inhibitors targeting a range of pathways including receptor tyrosine kinases (RTKs), MAPK pathway components, PI3K pathway components, cell cycle regulators, and others. The combination of MRTX1133 with each of the 28 small molecule inhibitors was evaluated for its effect on cell viability compared to each single agent alone. The combination of MRTX1133 with EGFR inhibitors (erlotinib and cetuximab) or PI3K$\alpha$ inhibitors (alpelisib and GDC-0077) demonstrated enhanced anti-tumor activity compared to each single agent alone (Fig.~5A). CRISPR-based screens were performed in the HPAC cell line using a custom library targeting 1,200 genes including known oncogenes, tumor suppressors, and genes involved in key signaling pathways. The combination of MRTX1133 with CRISPR-mediated knockout of EGFR or PI3K$\alpha$ also demonstrated enhanced anti-tumor activity compared to each single agent alone (Fig.~5B). These data suggest co-targeting KRAS$^{\mathrm{G12D}}$ with EGFR or PI3K$\alpha$ may represent a promising therapeutic strategy for patients with KRAS$^{\mathrm{G12D}}$-mutant cancers."""   

        },
        {
            "section_id": r"Drug-anchored CRISPR/Cas9 Screen Identifies Vulnerabilities and Modifiers of Response to MRTX1133 in KRAS$^{\mathrm{G12D}}$-Mutant Cancer Cell Lines \textit{In Vitro} and \textit{In Vivo}",
            "major_heading": "Results",
            "subheading_index": 8,
            "section_text":r"""To interrogate the role of selected genes in mediating the response of MRTX1133, an MRTX1133-anchored CRISPR/Cas9 screen in KRAS$^{\mathrm{G12D}}$-mutant cancer models was performed \textit{in vitro} and \textit{in vivo} (Fig.~S7A). The sgRNA libraries targeted $\sim 500$ (\textit{in vivo} library) or $\sim 1{,}000$ (\textit{in vitro} library) genes and included KRAS pathway and cancer-related genes. For the \textit{in vitro} screens, cells were treated with MRTX1133 concentrations approximating cellular viability IC$_{50}$ values (20--100 nM) to identify genes that augment the viability effect of MRTX1133 when deleted. \textit{In vitro}, sgRNAs targeting key cancer genes including KRAS, MYC, RPS6 and PTPN11 were decreased in both DMSO and MRTX1133-treated conditions and the extent of the reduction was similar to positive control, essential genes (Fig.~S7B). The sgRNA targeting the KRAS$^{\mathrm{G12D}}$-mutant sequence exhibited the greatest decreased abundance in the screens. sgRNAs targeting MYC, KRAS, RPS6, EGFR and PTPN11 genes were similarly depleted from vehicle and MRTX1133-treated tumors \textit{in vivo} indicating they are critical regulators of cell viability and also modify the response to MRTX1133 (Fig.~S7C). In addition, PIK3CA-targeting sgRNAs were depleted in the LS180 model. These data suggest co-targeting EGFR, PI3K$\alpha$ or SHP2 (PTPN11 gene) may complement KRAS$^{\mathrm{G12D}}$ inhibition and represent therapeutic strategies to augment the activity of MRTX1133.

            sgRNAs targeting several tumor suppressor genes, including \textit{PTEN}, \textit{KEAP1}, \textit{NF1} and \textit{RB1} were enriched in at least one \textit{in vitro} model with DMSO and/or MRTX1133 treatment. \textit{In vivo}, sgRNAs targeting \textit{TP53}, \textit{RB1} and \textit{KEAP1} were also enriched in vehicle and MRTX1133-treated tumors. These data confirm loss of these genes accelerates cancer cell growth and suggest loss of these genes may confer partial resistance to MRTX1133. Interestingly, sgRNAs targeting \textit{KEAP1} were strongly enriched \textit{in vivo} in the HPAC model and were not enriched \textit{in vitro} suggesting \textit{KEAP1} may be a key modifier locus and that KEAP1 tumor biology is not accurately modeled in cell culture conditions \textit{in vitro}. Enrichment of sgRNAs also indicates that KRAS can cooperate with key tumor suppressor pathways, including \textit{TP53}, \textit{RB1} and \textit{KEAP1}. Of note, in a preliminary analysis, the response rate of MRTX849 in NSCLC patients harboring mutations in both KRAS$^{\mathrm{G12C}}$ and \textit{KEAP1} was reduced compared to the response rate in KRAS$^{\mathrm{G12C}}$, \textit{KEAP1} WT patients [13, 14]."""
        },
        {
            "section_id": r"\textit{In Vitro} Combination Screens to Identify Targeted Strategies to Address KRAS Feedback and Resistance Pathways and Augment the Anti-tumor Efficacy of MRTX1133",
            "major_heading": "Results",
            "subheading_index": 9,      
            "section_text":r"""To identify targeted therapies capable of enhancing the response to MRTX1133, a 3-day combination viability screen was conducted \textit{in vitro} using a focused set of compounds targeting key cancer-related signal transduction nodes across a panel of KRAS$^{\mathrm{G12D}}$-mutant cell lines to identify synergistic and additive combinations as previously described [4, 15] (Fig.~S8A). Compounds were selected based on hits identified from CRISPR screens, relevance to KRAS-dependent signaling, and agents that are utilized for systemic treatment of human pancreatic and colorectal cancers. Consistent with observations for KRAS$^{\mathrm{G12C}}$ inhibition, combination with MEK and ERK inhibitors did not appear to enhance the activity of MRTX1133. In contrast to observations with KRAS$^{\mathrm{G12C}}$ inhibition, SHP2, SOS1, mTOR, and CDK4/6 inhibitors exhibited a more modest and a less consistent combinatorial effect with MRTX1133 in cell viability assays. The HER family inhibitors afatinib and cetuximab, as well as the PI3K$\alpha$ inhibitor BYL-719 demonstrated evidence of synergy with MRTX1133 across a significant fraction of evaluated cell lines, including the observation of broad combination synergy in both colon and pancreatic adenocarcinoma cell lines (Fig.~S8B and S8C).""" 
        },
        {
            "section_id": r"Cetuximab Enhances Inhibition of KRAS-dependent Signaling and Anti-tumor Activity of MRTX1133 in Pancreatic and Colon Tumor Models",
            "major_heading": "Results",
            "subheading_index": 10,
            "section_text":r"""Given the particular relevance of the EGFR pathway in the pathogenesis of pancreatic and colorectal cancers [16, 17], MRTX1133 and cetuximab were evaluated in multiple cell line-derived colon or pancreatic cancer xenografts with varying sensitivity to MRTX1133 as a monotherapy. The combination of cetuximab and MRTX1133 improved anti-tumor efficacy compared to either single agent in all 7 tumor models evaluated (Fig.~5A, 5C, S9A, and S9B). Of note, cetuximab did not demonstrate meaningful anti-tumor activity as a monotherapy in all but one model in line with its notable lack of activity in KRAS-mutant CRC patients [18]. Immunohistochemistry coupled with quantitative image analyses demonstrated treatment with MRTX1133 plus cetuximab led to near complete inhibition of cancer cell-specific pERK and pS6 following 7 days of administration in the AsPC-1 pancreatic cancer model, whereas treatment with either single agent led to sub-maximal inhibition (Fig.~5B and S9C). In the LS180 CRC model, MRTX1133 anti-tumor activity was explored using a 30 mg/kg BID intermittent schedule of 2 treatment days followed by 5 days off. When combining this schedule of MRTX1133 with cetuximab on a Q3D schedule, there was a significant improvement in anti-tumor activity (80\% TGI) compared with either single agent (Fig.~S9A). In addition, immunohistochemical analysis of tumor tissue demonstrated complete inhibition of pS6 at 24 hrs with MRTX1133 plus cetuximab, while submaximal inhibition was achieved with either single agent (Fig.~S9D). A comparable effect was observed in the GP2D colon cancer model with complete inhibition of pERK and pS6 achieved at 6 and 24 hours after treatment with MRTX1133 BID plus cetuximab, while treatment with either single agent resulted in sub-maximal inhibition (Fig.~5D). In both the AsPC-1 and LS180 models, tumor RNA sequencing indicated that the combination of MRTX1133 and cetuximab demonstrated a more pronounced impact on selected GSEA signatures including KRAS signaling UP and MYC target gene sets as well as individual MAPK-dependent target genes including DUSP4 and 6, ETV4 and 5, SPRY4, and PHLDA1 compared with either single agent illustrating a more comprehensive inhibition of the RAS/ERK-dependent transcriptional program for the combination (Fig.~S10A and S10B). Similarly, the combination demonstrated higher magnitude impact on the expression of selected target genes implicated in regulation of E2F transcriptional program/cell cycle and selected apoptosis regulatory genes compared with either single agent (Fig.~S10C). These data illustrate the participation of EGFR upstream of KRAS pathway signaling and provide a combinatorial strategy to further inhibit KRAS-mediated signaling and enhance anti-tumor efficacy in KRAS$^{\mathrm{G12D}}$-mutated tumors."""
        },
        {

            "section_id": r"MRTX1133 Combined with BYL-719 Provides Improved Anti-tumor Response in Pancreatic and Colon Tumor Models",
            "major_heading": "Results",
            "subheading_index": 11,
            "section_text":r"""PI3K$\alpha$ is both a key regulator and effector of KRAS-dependent signaling and is also activated through mutations involving the \textit{PIK3CA} gene locus in colorectal cancer, including mutations co-occurring with KRAS [19]. In addition, \textit{PTEN} sgRNAs were enriched in drug-anchored CRISPR screens and lower \textit{PTEN} expression exhibited a trend towards resistance to MRTX1133 in CDX/PDX models suggesting dysregulated PI3K pathway signaling may limit the therapeutic response to KRAS$^{\mathrm{G12D}}$ inhibition. Furthermore, BYL-719 was one of the top hits from \textit{in vitro} combination screens further suggesting that PI3K signaling represents a collateral dependency in the context of KRAS activation. \textit{In vitro}, MRTX1133 and BYL-719 each both potently inhibited AKT phosphorylation on serine 473 and the extent of inhibition was further increased in combination in GP2D, LS180, and AsPC-1 cell lines (Fig.~S8C). \textit{In vivo}, the combination of MRTX1133 and BYL-719 demonstrated increased anti-tumor activity in both CRC models (\textit{PIK3CA} H1047-mutant GP2D and LS180) and a pancreatic cancer model (AsPC-1) compared with either single agent (Fig.~6). In addition, increased inhibition of RAS activity was observed at 6 and 24 hours after BID administration for the combination compared with either single agent in the LS180 and AsPC-1 models (Fig.~6A and 6C). Consistent with inhibition of activated RAS in these two models, greater inhibition of pERK and pAKT was observed for the combination (Fig.~6A and 6C). In the LS180 model, which is relatively insensitive to MRTX1133 monotherapy, the combination demonstrated more durable pAKT inhibition in tumor lysates after BID $\times$ 7 days of treatment demonstrating that the combination can overcome the reactivation of key signaling pathways observed following KRAS$^{\mathrm{G12D}}$ inhibition alone (Fig.~S11A). In the relatively sensitive AsPC-1 model, analysis of pERK and pAKT in tumor lysates after BID $\times$ 7 days indicated a greater magnitude of inhibition of these phospho-proteins in combination compared with either single agent (Fig.~S11B). These data support the role of PI3K$\alpha$ in modifying KRAS-dependent signaling in colon and pancreatic cancers harboring KRAS$^{\mathrm{G12D}}$ mutations and the potential utility of combining PI3K$\alpha$ inhibitors with MRTX1133 in these cancers."""             
        },
        {
            "section_id": r"Discussion",
            "major_heading": "Discussion",
            "subheading_index": 1,
            "section_text":r"""The development of KRAS$^{\mathrm{G12C}}$ inhibitors has illustrated a breakthrough advancement in strategies to develop targeted therapies directed at oncogenic proteins previously believed to be undruggable and has also provided a much-needed treatment option for patients harboring this particular \textit{KRAS} mutation. The increased understanding of nucleotide cycling dynamics for different \textit{KRAS} mutations as well as key structural elements of the KRAS switch II pocket has allowed discovery scientists to contemplate inhibitors of additional RAS mutant variants. KRAS$^{\mathrm{G12D}}$ is a particularly compelling target for the design of mutant-selective KRAS inhibitors based on a 3-fold higher mutation frequency in human cancers compared with KRAS$^{\mathrm{G12C}}$, a favorable GTP-hydrolysis rate compared with other non-KRAS$^{\mathrm{G12C}}$ mutations to enable targeting the inactive conformation of KRAS, and the ability to utilize the residue 12 glycine-to-aspartic acid mutational alteration to enable molecular interactions with the polar aspartate R group side chain to achieve selectivity vs KRAS$^{\mathrm{WT}}$. However, there are also significant barriers to overcome to facilitate development of KRAS$^{\mathrm{G12D}}$ inhibitors with sufficient drug-like potency to support advancement to clinical development. These challenges include the observation that KRAS$^{\mathrm{G12C}}$ inhibitors identified to date have intrinsic binding affinity in the micromolar range and require covalent modification of the mutated cysteine residue to achieve drug-like potency. KRAS$^{\mathrm{G12D}}$ lacks a reactive residue to enable development of covalent small molecule inhibitors, thus it is predicted that a novel approach to increase intrinsic binding affinity several orders of magnitude would be required to effectively target this mutant variant. Despite these challenges, an in-depth analysis of binding modes derived from crystal structures allowed small molecule inhibitor optimization to optimally occupy the switch II pocket through exploiting non-classical hydrogen bonding and ion pair interactions, and to ultimately increase binding affinity toward the intended therapeutic target by more than 1,000,000-fold relative to initial lead molecules. This drug discovery and lead optimization strategy culminated in the discovery of MRTX1133 as a KRAS$^{\mathrm{G12D}}$ inhibitor with picomolar binding affinity and $\sim 1{,}000$-fold selectivity compared with KRAS$^{\mathrm{WT}}$, which is described in detail in Wang et al.~[10].

            MRTX1133 demonstrated approximately $1{,}000$-fold selectivity for KRAS$^{\mathrm{G12D}}$ compared with KRAS$^{\mathrm{WT}}$ or other KRAS mutant variants in both biochemical and cellular assays. Selectivity of KRAS$^{\mathrm{G12C}}$ inhibitors is driven by electrophilic KRAS inhibitors that can form irreversible covalent bonds with the nucleophilic sulfur atom of Cys12. MRTX1133 was designed as a KRAS$^{\mathrm{G12D}}$ selective inhibitor based on structural understanding that critical switch II pocket binding interactions are conserved across KRAS variants in concert with the principle that small molecule substituents with a protonated amine moiety proximal to the acidic side chain Asp12 could result in a productive interaction to drive selectivity for this mutant protein. The design of MRTX1133 utilizing a C4 bridged [3.2.1] bicyclic diamino piperazine substituent which both forms a non-classical hydrogen bond with the Gly10 carbonyl oxygen and positions the charged secondary amine to achieve an optimal and selective interaction with Asp12 and Gly60 while sparing KRAS$^{\mathrm{WT}}$. MRTX1133 demonstrated robust anti-tumor activity at well-tolerated doses in mice administered IP at up to 30 mg/kg twice daily for up to 28 days with no evidence of weight loss or overt signs of toxicity. As the consequences for targeting KRAS$^{\mathrm{WT}}$ in adult mammalian species is unknown, the ability of MRTX1133 to selectively target KRAS$^{\mathrm{G12D}}$ and achieve a sufficient therapeutic index to allow near complete inhibition of KRAS-dependent signaling may be critical in the development of KRAS targeted therapies.

            MRTX1133 provides a renewed opportunity to explore how KRAS$^{\mathrm{G12D}}$ functions in a biochemical and cellular context and to increase understanding of the contextual role of oncogenic \textit{KRAS}$^{\mathrm{G12D}}$ mutations in driving the pathogenesis and progression of distinct cancer types. KRAS$^{\mathrm{G12D}}$ mutations are most commonly observed in pancreatic ductal adenocarcinoma (36\%, [20]) and colorectal cancers (12\%, [21]) and are also found in lung, endometrial and other cancers. Based on the prevalence of KRAS$^{\mathrm{G12D}}$ mutations in PDAC and CRC and availability of disease models harboring these mutations, studies in the present manuscript focused on these cancer types. The observation that MRTX1133 potently impacted viability in the vast majority of KRAS$^{\mathrm{G12D}}$ mutated cell lines evaluated \textit{in vitro} indicates that this variant can broadly act as an oncogenic driver. However, studies evaluating the anti-tumor activity of KRAS$^{\mathrm{G12C}}$ inhibitors indicated that the dependence of cells on \textit{KRAS} mutations for growth and survival as oncogenic drivers was distinct in \textit{in vitro} cell lines compared with \textit{in vivo} model systems [4, 22]. The evaluation of MRTX1133 anti-tumor activity in cell line- or patient-derived tumor xenograft models indicated that marked tumor regression was observed in 8/11 PDAC and 2/8 CRC models. This data suggests that KRAS$^{\mathrm{G12D}}$ functions as a consistently strong oncogenic driver in PDAC; however, may act as a more heterogeneous or contextual oncogenic driver in CRC. Recent data from clinical trials evaluating the KRAS$^{\mathrm{G12C}}$ inhibitor, adagrasib, as a monotherapy also suggested a similar distinction in the response of patients in different cancer types with RECIST objective responses observed in 5/10 (50\%) patients with PDAC and 10/45 (22\%) with CRC.

            Understanding mechanistic differences of \textit{KRAS} alleles and tissue origin are crucial to develop effective treatment strategies for KRAS-dependent cancers. First, \textit{KRAS} mutations are often a founder genetic event involved in the pathogenesis of PDAC and are consistently found in precancerous pancreatic intraepithelial neoplasms; however, may be acquired as later events during systemic treatment for metastatic disease and have been found as subclonal genetic alterations in a subset of CRC patients [25--27]. Second, distinct subsets of CRC are characterized by chromosomal instability (CIN) or microsatellite instability (MSI) and are among cancers that exhibit a moderately high tumor mutation burden (TMB) suggesting an extensive degree of genetic heterogeneity [28]. In contrast, PDAC is characterized by a lower overall tumor mutation burden and chromosomal instability. Finally, CRC is characterized by extensive genomic heterogeneity and several defined subtypes based on mutational patterns, including partially overlapping subsets with distinct oncogenic alterations in \textit{KRAS}, \textit{PIK3CA}, \textit{BRAF} and selected receptor tyrosine kinases [29]. In contrast, PDAC mutations are categorically more homogenous with the majority of cases comprised of co-occurring \textit{KRAS}, \textit{TP53}, \textit{CDKN2A}, and \textit{SMAD4} alterations genes/pathways with a smaller subset exhibiting gene alterations involved in chromatin remodeling or DNA repair pathways. Together, these data indicate \textit{KRAS} mutations are an early founder genetic event in PDAC and may function as a more homogenous oncogenic driver in this setting whereas \textit{KRAS} mutations can be acquired as a later genetic event and/or in the context of genomic instability and co-occurring mutations that modify the dependency on KRAS in CRC.

            Another factor that is critical in demonstrating a maximal anti-tumor response to direct KRAS inhibition is related to the ability to demonstrate deep and durable inhibition of KRAS-dependent signaling, particularly the ERK pathway, throughout dosing intervals. The ability to achieve deep and durable inhibition of KRAS-dependent signaling is dependent on the susceptibility of \textit{KRAS}-mutated tumor cells to feedback reactivation of KRAS and pathways that mediate KRAS-dependent signaling [30, 31]. Prior studies with KRAS$^{\mathrm{G12C}}$, RAF, and MEK inhibitors indicated that blockade of KRAS-dependent signaling activated a transcriptional program suppressing \textit{DUSP}, \textit{SPRY}, and \textit{ETV} family genes which cooperate to mediate increased signaling flux through RTK, SOS, and MEK/ERK family members resulting in conditional bypass dependence on KRAS [4, 32--34]. The susceptibility of \textit{KRAS}-mutated tumor cells to KRAS pathway inhibition can be influenced by multiple factors which poise cells for feedback reactivation of KRAS-dependent signaling including the expression or induction of HER family RTKs or the presence of co-occurring genetic alterations such as RTK amplification or mutations involving \textit{STK11}, \textit{PTEN}, or \textit{PIK3CA} gene loci. In the present studies, suppression of \textit{DUSP}, \textit{SPRY}, and \textit{ETV} family transcripts along with evidence of partial susceptibility to time-dependent feedback reactivation of ERK and S6 was observed in GP2D, HPAC, and Panc 04.03 cell lines and/or tumor models. Evaluation of KRAS-dependent signaling in the HPAC tumor model also indicated evidence of rebound of ERK and S6 phosphorylation at lower dose levels which correlated with the extent of anti-tumor efficacy and illustrated the importance of durable inhibition of this pathway. Interestingly, despite the evidence of ERK reactivation observed, tumor regression of 40\% or greater was observed at higher dose levels in all 3 of these models indicating that partial and transient pathway inhibition was sufficient for cytoreductive anti-tumor activity.

            Although marked tumor regression was observed in multiple tumor models, evaluation of time- and dose-dependent signaling indicated that recovery of KRAS-dependent signaling may limit the magnitude and duration of response to MRTX1133. To better understand factors that may limit MRTX1133 anti-tumor activity, chemical genomics-based combinatorial screens and drug-anchored CRISPR/Cas9 screens were utilized to systematically determine collateral dependencies which modify response to KRAS$^{\mathrm{G12D}}$ inhibition. Consistent with observations in studies conducted with KRAS$^{\mathrm{G12C}}$ inhibitors, EGFR/HER family, S6 pathway and SHP2 were identified as co-inhibitory strategies with potential to augment the response to MRTX1133. Together, these observations support the hypothesis that KRAS$^{\mathrm{G12D}}$ mutated cells are susceptible to feedback pathways that reactivate signaling upstream of KRAS and that co-targeting these pathways may enhance MRTX1133 anti-tumor activity. In contrast to observations following KRAS$^{\mathrm{G12C}}$ inhibition, SHP2 and SOS1 inhibitors exhibited a more modest and a less consistent combinatorial effect with MRTX1133 and CDK4/6 exhibited a minimal combination effect in cell viability assays. The lack of combination activity with the CDK4/6 inhibitor, palbociclib, is consistent with the observation that \textit{CDKN2A} loss of function mutations exhibited a trend towards a positive association with sensitivity to MRTX1133 in the panel of tumor models \textit{in vivo} suggesting enhanced blockade of early cell cycle transition may be less effective with KRAS$^{\mathrm{G12D}}$ inhibitors.

            One interesting contrast with prior experience with KRAS$^{\mathrm{G12C}}$ inhibitors is provided by the observation that MRTX1133 can bind to the active state of KRAS$^{\mathrm{G12D}}$ based on biochemical and crystallographic evidence. Binding to active form (even though active) impairs a productive effector interface thereby blocking downstream signaling as supported by the crystal structure and the HTRF effector interaction assay. This observation suggests targeting the active state of KRAS is feasible and this may partially overcome the $\sim 2$-fold lower intrinsic GTP hydrolysis rate for KRAS$^{\mathrm{G12D}}$ compared with KRAS$^{\mathrm{G12C}}$ [7]. Additionally, the ability of MRTX1133 to bind to the active state may partially offset the relative combinatorial effect with SHP2 and SOS1 inhibitors as these strategies regulate SOS1-dependent guanine nucleotide exchange and are predicted to more effectively augment the effect of inhibitors that bind exclusively to the inactive state of KRAS (e.g., KRAS$^{\mathrm{G12C}}$ inhibitors). Although KRAS$^{\mathrm{G12D}}$ exhibits a $\sim 2$-fold lower intrinsic GTP hydrolysis rate for KRAS$^{\mathrm{G12D}}$ compared with KRAS$^{\mathrm{G12C}}$, this mutant variant exhibits the highest rate of GAP-mediated GTP hydrolysis of all evaluated KRAS mutations [7]. Although studies with MRTX849 indicated that combination with EGFR inhibitors was broadly effective [4], synergy score calculations \textit{in vitro} and depth of combination response \textit{in vivo} suggest that KRAS$^{\mathrm{G12D}}$ mutated tumors may be relatively more susceptible to EGFR/HER family-based co-targeting strategies. It should be noted, that targeting SOS1 (and SHP2) would mostly be predicted to singularly impinge on regulating GTP hydrolysis by regulating extrinsic guanine nucleotide exchange whereas targeting EGFR/HER family would impact both nucleotide exchange and extrinsic GAP-mediated GTP hydrolysis which is consistent with the observations of differential combinatorial impact of cetuximab, SHP2, and SOS1 inhibitors in the present studies. Studies with adagrasib, a KRAS$^{\mathrm{G12C}}$ inhibitor in combination with cetuximab in CRC demonstrated a RECIST objective response rate nearly double compared with adagrasib monotherapy indicating that KRAS/EGFR inhibitor combination is a clinically validated concept [24].

            Finally, the observation that the PI3K$\alpha$ inhibitor, BYL719, was effective in combination with MRTX1133 in cell-based screens and \textit{in vivo} tumor models represents another divergent observation for KRAS$^{\mathrm{G12D}}$ inhibition compared with KRAS$^{\mathrm{G12C}}$ inhibition. Studies conducted with MRTX849 in KRAS$^{\mathrm{G12C}}$ mutated nonclinical tumor cell lines and \textit{in vivo} models generally demonstrated a lack of effectiveness for the combination with BYL719 [4]. In contrast, the combination of MRTX849 with mTOR inhibitors demonstrated significant anti-tumor efficacy compared with either single agent in all 6 KRAS$^{\mathrm{G12C}}$-mutated NSCLC tumor models evaluated. There are multiple plausible explanations for the distinct combinatorial effectiveness observed through targeting PI3K$\alpha$ directly in KRAS$^{\mathrm{G12D}}$-mutated tumors versus targeting mTOR downstream in KRAS$^{\mathrm{G12C}}$-mutated tumors including the prevalence of KRAS$^{\mathrm{G12D}}$ and KRAS$^{\mathrm{G12C}}$ mutations in different tumor types as well as differential effector interactions between these two oncogenic \textit{KRAS} mutations. Targeting mTOR in combination with MRTX849 was effective in KRAS$^{\mathrm{G12C}}$-mutated NSCLC models and generally ineffective in CRC models highlighting potential tumor-specific differences [4]. It is notable that \textit{STK11} loss of function mutations that dysregulate mTOR are enriched and occur in approximately one third of KRAS-mutated NSCLC and that \textit{PIK3CA} and \textit{PTEN} mutations are significantly mutually exclusive with \textit{KRAS} mutations in NSCLC [35]. In contrast, \textit{PIK3CA} mutations are enriched and occur in approximately 25\% of KRAS-mutated CRC and \textit{PTEN} is mutated or lost in an additional 7\% of tumors [21]. Although \textit{PIK3CA}, \textit{PTEN}, or \textit{STK11} are rarely mutated in PDAC, the critical role of insulin and insulin-like growth factor signaling in both PDAC pathogenesis and activation of PI3K-dependent signaling provides a basis for the importance of co-targeting KRAS and PI3K$\alpha$ in this cancer type [36--38]. These critical differences in co-occurring genetic alterations and disease biology in distinct KRAS-mutated cancer types provide a rationale for alternative combination strategies in these disease settings. In addition, there have been multiple reports demonstrating differences in the ability of KRAS$^{\mathrm{G12D}}$ to more effectively facilitate PI3K effector interactions and pathway activation compared with KRAS$^{\mathrm{G12C}}$ or other KRAS variants providing further rationale for the co-targeting strategy with direct PI3K$\alpha$ inhibitors in KRAS$^{\mathrm{G12D}}$ mutant cancers independently of tumor type [39, 40].

            Together, these data indicate that discovery and preclinical development of high-affinity, mutation-selective, non-covalent inhibitors of KRAS$^{\mathrm{G12D}}$ and perhaps other KRAS mutant variants is feasible. As KRAS$^{\mathrm{G12D}}$ is the most prevalent of \textit{KRAS} mutant alleles, the translation of these findings to a reality for cancer patients harboring KRAS$^{\mathrm{G12D}}$ mutations would be highly impactful. Additionally, the anticipated therapeutic index for allele-specific inhibitors may provide an advantage in both facilitating maximal target inhibition and a favorable combinatorial therapy profile. These studies also provide insight toward the function of this mutation as an oncogenic driver in different tumor types and in the context of co-occurring genetic alterations. The ability to also characterize the effect of MRTX1133 on KRAS-dependent signaling and feedback pathways utilizing molecular profiling approaches and functional genomics helps increase understanding of KRAS signaling dynamics in general as well as unique aspects of KRAS$^{\mathrm{G12D}}$ signaling. In turn, the understanding of KRAS$^{\mathrm{G12D}}$ signaling dynamics provides rational perspective on co-targeting of collateral dependencies. Collectively, the present studies provide renewed perspective on direct targeting strategies for KRAS and provide defining strategies to identify patients likely to benefit from single agent or rationally directed combinations."""
        },
        {
            "section_id": r"Reagents and Cell Lines",
            "major_heading": "Materials and Methods",
            "subheading_index": 1,
            "section_text":r"""MRTX1133 was synthesized at WuXi AppTec (Wuhan, China). MRTX1133 in powder form was stored at room temperature and protected from light. MRTX1133 was formulated in 100\% DMSO and aliquoted for long-term storage at $-20^\circ$C. Roswell Park Memorial Institute 1640 medium (RPMI; \#11875-093), Dulbecco's Modified Eagle's Medium (DMEM; \#10566-016), penicillin and streptomycin (\#15070-063), HEPES ((4-(2-hydroxyethyl)-1-piperazineethanesulfonic acid); \#15630-080), Dulbecco's Phosphate-buffered Saline (DPBS; \#14190-136) and sodium pyruvate (\#11360-070) were obtained from Gibco/Thermo Fisher Scientific (Waltham, MA). Fetal Bovine Serum (FBS) was obtained from Corning (\#35-011-CV, Corning, NY). HPAF-II, HEC-1-B, AGS, A427, LS-180, SNU-C2B, LS513, SU.86.86, Panc-1, Panc 08.13, Panc 02.03, Panc 10.05, SW 1990, Panc 04.03, Panc 05.04, HPAC and AsPC-1 cell lines were obtained from American Type Culture Collection (ATCC; Manassas, VA). The SUIT-2 and KP-4 cell lines were obtained from National Institutes of Biomedical Innovation, Health and Nutrition JCRB Cell Bank (Japanese Collection of Research Bioresources; Sekisui XenoTech, LLC). The SNU-1033, SNU-61, SNU-1197, HCC-1588 and SNU-410 cell lines were obtained from KCLB (Korean Cell Line Bank; Seoul, Korea). The GP2D cell line was obtained from Sigma/Millipore (St. Louis, MO). The SNU-407 cell line was obtained from AddexBio (San Diego, CA). The COLO-678 cell line was obtained from Deutsche Sammlung von Mikroorganismen und Zellkulturen (DSMZ; Braunschweig, Germany). Human cancer cell lines were maintained at $37^\circ$C in a humidified incubator at 5\% CO$_2$."""
        },
        {
            "section_id": r"\textit{In Vivo} Studies",
            "major_heading": "Materials and Methods",
            "subheading_index": 2,
            "section_text":r"""All mouse studies were conducted in compliance with all applicable regulations and guidelines of the Institutional Animal Care and Use Committee (IACUC) from the National Institutes of Health (NIH). Mice were maintained under pathogen-free conditions, and food and water was provided \textit{ad libitum}. 6--8-week-old, female, athymic nude-\textit{Foxn1}$^{\mathrm{nu}}$ mice (Envigo, San Diego) were injected subcutaneously with tumor cells in 100 $\mu$L of PBS and Matrigel matrix in the right hind flank with $5.0 \times 10^6$ cells (Corning \#356237; Discovery Labware, MA) 50:50 cells:Matrigel. For the orthotopic implants, AsPC-1 luciferase-tagged cells were implanted orthotopically in the pancreas with $5.0 \times 10^6$ cells in 50 $\mu$L of 1:1 Matrigel/serum-free media. Mouse health was monitored daily. For the subcutaneous implants, caliper measurements began when tumors were palpable. Tumor volume measurements were determined utilizing the formula $0.5 \times L \times W^2$ in which $L$ refers to length and $W$ refers to width of each tumor. When tumors reached an average tumor volume of $\sim 200$--$400$ mm$^3$, mice were randomized into treatment groups. For the cell line implanted orthotopically, bioluminescent images (BLI) were acquired every 5--8 days for 5 weeks, using luciferin (150 mg/kg, 0.01 mL/g) with images acquired 10 minutes post luciferin injection. Mice were treated by IP injection with either vehicle consisting of 10\% research grade Captisol (CyDex Pharmaceuticals, KS) in 50 mM citrate buffer pH 5.0 or MRTX1133 in vehicle at indicated doses. For efficacy studies, animals were IP administered MRTX1133 or vehicle and monitored daily, tumors were measured 3 times per week and body weights were measured 2 times per week. Study Day on efficacy plots indicates the day after which MRTX1133 treatment was initiated. To analyze BLI, Region of Interest (ROI) analysis was completed using VivoQuant\textsuperscript{\texttrademark} (Invicro, A Konica Minolta Company) software. Pancreas ROIs were generated using a fixed-area ellipsoid and were placed on relevant BLI signal areas, using prone and supine photograph images for anatomical reference. Abdomen ROIs were generated using a fixed-area rectangle, with anatomical reference as above. BLI signals in images were scaled in units of radiance, defined as photons per second per square millimeter per steradian (p/s/mm$^2$/sr). Python\textsuperscript{\texttrademark} (Python Software Foundation) software was used to generate relevant plots based on quantification performed in VivoQuant\textsuperscript{\texttrademark}.

            For studies conducted at Crown Biosciences China, 4--5-week-old female BALB/c nude mice or NOD/SCID mice were implanted with tumor fragments 2--3 mm in diameter into the right flank via trocar implantation. Mice were randomized, and dosing was initiated when the mean tumor volume was approximately 300 mm$^3$. Eight mice were dosed with either vehicle alone (10\% Captisol in 10 mM citrate buffer, pH 5.0; Teknova, Hollister, CA; \#Q2443) or 30 mg/kg MRTX1133 twice daily by intraperitoneal injection for the number of days indicated ($n = 4$ per group).

            Statistical analysis of differences in mean tumor volume between vehicle and MRTX1133-treated cohorts was run using ANOVA in Excel (Microsoft; Redmond, WA) or GraphPad Prism (GraphPad; San Diego, CA). A $P$-value $< 0.05$ was considered statistically significant. Individual tumors were used for replicates, as opposed to the same tumor run multiple times."""
        }
    ]
}

with open("data/papers/PMID_36216931/raw_text.json", "w") as f:
    json.dump(data, f, indent=4)